<?php
/**
 * Code editor tab
 *
 * Allows the user to add custom JavaScript code that runs after the main widget code.
 *
 * @package AbjadWidget
 * @subpackage Admin
 */

// No need to instantiate the admin class anymore.
$code_options = get_option('abjad_widget_code', array('custom_js' => ''));
?>

<div class="wrap abjad-code-editor-page">
    <h1><?php _e('Code Editor', 'abjad-widget-admin'); ?></h1>
    
    <div class="notice notice-warning">
        <p>
            <strong><?php _e('WARNING', 'abjad-widget-admin'); ?>:</strong>
            <?php _e('Add custom JavaScript to modify widget behavior. Wrong code may break the widget!', 'abjad-widget-admin'); ?>
        </p>
    </div>
    
    <div class="notice notice-info">
        <p>
            <strong>🔧 <?php _e('Widget Architecture', 'abjad-widget-admin'); ?>:</strong>
            <?php _e('Widget JavaScript is dynamically generated by', 'abjad-widget-admin'); ?> 
            <code>abjadwidget-js.php</code>. 
            <?php _e('The code you write here runs AFTER the main widget code and can override or extend existing functions.', 'abjad-widget-admin'); ?>
        </p>
        <p>
            <strong><?php _e('Available Global Variables', 'abjad-widget-admin'); ?>:</strong><br>
            <code>window.abjadWidgetConfig</code> – <?php _e('Widget configuration (color, position, button content)', 'abjad-widget-admin'); ?><br>
            <code>window.abjadWidgetI18n</code> – <?php _e('Translation strings', 'abjad-widget-admin'); ?><br>
            <code>window.abjadWidgetCustomCSS</code> – <?php _e('Custom CSS (defined in Style Editor)', 'abjad-widget-admin'); ?>
        </p>
        <p>
            <strong><?php _e('Example Usage', 'abjad-widget-admin'); ?>:</strong><br>
            <code>// Log a message when the button is clicked</code><br>
            <code>jQuery(document).on('click', '.aw-button', function() { console.log('Widget clicked!'); });</code>
        </p>
    </div>
    
    <form method="post" action="options.php">
        <?php settings_fields('abjad_widget_code_options'); ?>
        
        <div class="abjad-editor-container">
            <div class="abjad-editor-header">
                <h3><?php _e('Your Custom JavaScript', 'abjad-widget-admin'); ?></h3>
                <p class="description">
                    <?php _e('This code will be executed AFTER the main widget code.', 'abjad-widget-admin'); ?>
                </p>
            </div>
            
            <div class="abjad-editor-main">
                <textarea id="custom_js" 
                          name="abjad_widget_code[custom_js]" 
                          class="large-text code" 
                          rows="20"
                          placeholder="<?php echo esc_attr__('// Write your custom JavaScript here', 'abjad-widget-admin'); ?>"><?php echo esc_textarea($code_options['custom_js']); ?></textarea>
            </div>
            
            <div class="abjad-editor-footer">
                <p class="description">
                    <strong><?php _e('Important', 'abjad-widget-admin'); ?>:</strong><br>
                    • <?php _e('Your code runs after the main widget code.', 'abjad-widget-admin'); ?><br>
                    • <?php _e('You cannot directly modify the core widget functions, but you can call them.', 'abjad-widget-admin'); ?><br>
                    • <?php _e('Faulty code may break the widget. Always backup before making changes.', 'abjad-widget-admin'); ?>
                </p>
            </div>
        </div>
        
        <?php submit_button(__('Save JavaScript', 'abjad-widget-admin')); ?>
    </form>
    
    <div class="abjad-code-reference">
        <h3><?php _e('Available Widget Functions', 'abjad-widget-admin'); ?></h3>
        <table class="wp-list-table widefat fixed striped">
            <thead>
                <tr>
                    <th><?php _e('Function', 'abjad-widget-admin'); ?></th>
                    <th><?php _e('Description', 'abjad-widget-admin'); ?></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><code>calculations('abjad')</code></td>
                    <td><?php _e('Triggers Abjad calculation', 'abjad-widget-admin'); ?></td>
                </tr>
                <tr>
                    <td><code>calculations('bastet')</code></td>
                    <td><?php _e('Triggers Bastet calculation', 'abjad-widget-admin'); ?></td>
                </tr>
                <tr>
                    <td><code>calculations('huddam')</code></td>
                    <td><?php _e('Triggers Huddam calculation', 'abjad-widget-admin'); ?></td>
                </tr>
                <tr>
                    <td><code>switchTab(tabId)</code></td>
                    <td><?php _e('Switches between tabs (abjad/bastet/huddam/settings/support)', 'abjad-widget-admin'); ?></td>
                </tr>
                <tr>
                    <td><code>getSetting(id)</code></td>
                    <td><?php _e('Reads a widget setting', 'abjad-widget-admin'); ?></td>
                </tr>
                <tr>
                    <td><code>setSetting(id, value)</code></td>
                    <td><?php _e('Changes a widget setting', 'abjad-widget-admin'); ?></td>
                </tr>
                <tr>
                    <td><code>__(key)</code></td>
                    <td><?php _e('Returns a translated string', 'abjad-widget-admin'); ?></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<style>
.abjad-code-editor-page .CodeMirror {
    border: 1px solid #ccd0d4;
    height: auto;
    max-height: 500px;
    font-family: 'Monaco', 'Menlo', 'Consolas', monospace;
    font-size: 13px;
    line-height: 1.5;
    border-radius: 4px;
}

.abjad-code-editor-page .CodeMirror-gutters {
    background: #f8f9fa;
    border-right: 1px solid #ccd0d4;
}

.abjad-code-editor-page .CodeMirror-linenumber {
    color: #666;
}

.abjad-editor-container {
    background: #fff;
    border: 1px solid #ccd0d4;
    border-radius: 4px;
    margin: 20px 0;
}

.abjad-editor-header {
    padding: 15px 20px;
    border-bottom: 1px solid #ccd0d4;
    background: #f8f9fa;
}

.abjad-editor-header h3 {
    margin: 0 0 10px 0;
}

.abjad-editor-main {
    padding: 20px;
}

.abjad-editor-footer {
    padding: 15px 20px;
    border-top: 1px solid #ccd0d4;
    background: #f8f9fa;
}

.abjad-code-reference {
    margin-top: 30px;
    background: #fff;
    border: 1px solid #ccd0d4;
    border-radius: 4px;
    padding: 20px;
}

.abjad-code-reference h3 {
    margin-top: 0;
}

.abjad-code-reference table {
    margin-top: 15px;
}

.abjad-code-reference code {
    background: #f1f1f1;
    padding: 2px 5px;
    border-radius: 3px;
    font-size: 12px;
}

.notice-info {
    border-left-color: #00a0d2;
    background: #f7fcfe;
}
</style>

<script>
jQuery(document).ready(function($) {
    if (typeof wp.codeEditor !== 'undefined') {
        var editor = wp.codeEditor.initialize($('#custom_js'), {
            codemirror: {
                mode: 'javascript',
                lineNumbers: true,
                lineWrapping: true,
                theme: 'default',
                autoCloseBrackets: true,
                matchBrackets: true,
                indentUnit: 4,
                tabSize: 4,
                indentWithTabs: true,
                extraKeys: {
                    'Ctrl-Space': 'autocomplete',
                    'Ctrl-S': function() {
                        $('form').submit();
                    }
                }
            }
        });
        
        var jsEditor = editor.codemirror;
        
        jsEditor.on('change', function() {
            // No auto-save
        });
    }
    
    $('form').on('submit', function(e) {
        var jsCode = $('#custom_js').val();
        if (jsCode.includes('</script>')) {
            if (!confirm('<?php echo esc_js(__('Your code contains a </script> tag. This may break the widget. Continue?', 'abjad-widget-admin')); ?>')) {
                e.preventDefault();
                return false;
            }
        }
        return true;
    });
});
</script>
