<?php
/**
 * Code editor tab
 *
 * Allows the user to add custom JavaScript code that runs after the main widget code.
 *
 * @package AbjadWidget
 * @subpackage Admin
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly.
}

$abjad_widget_code_options = get_option( 'abjad_widget_code', array( 'custom_js' => '' ) );
?>

<div class="wrap abjad-code-editor-page">
    <h1><?php esc_html_e( 'Code Editor', 'abjad-widget' ); ?></h1>

    <div class="notice notice-warning">
        <p>
            <strong><?php esc_html_e( 'WARNING', 'abjad-widget' ); ?>:</strong>
            <?php esc_html_e( 'Add custom JavaScript to modify widget behavior. Wrong code may break the widget!', 'abjad-widget' ); ?>
        </p>
    </div>

    <div class="notice notice-info">
        <p>
            <strong>🔧 <?php esc_html_e( 'Widget Architecture', 'abjad-widget' ); ?>:</strong>
            <?php esc_html_e( 'Widget JavaScript is dynamically generated by', 'abjad-widget' ); ?> 
            <code>abjadwidget-js.php</code>. 
            <?php esc_html_e( 'The code you write here runs AFTER the main widget code and can override or extend existing functions.', 'abjad-widget' ); ?>
        </p>
        <p>
            <strong><?php esc_html_e( 'Available Global Variables', 'abjad-widget' ); ?>:</strong><br>
            <code>window.abjadWidgetConfig</code> – <?php esc_html_e( 'Widget configuration (color, position, button content)', 'abjad-widget' ); ?><br>
            <code>window.abjadWidgetI18n</code> – <?php esc_html_e( 'Translation strings', 'abjad-widget' ); ?><br>
            <code>window.abjadWidgetCustomCSS</code> – <?php esc_html_e( 'Custom CSS (defined in Style Editor)', 'abjad-widget' ); ?>
        </p>
        <p>
            <strong><?php esc_html_e( 'Example Usage', 'abjad-widget' ); ?>:</strong><br>
            <code>// Log a message when the button is clicked</code><br>
            <code>jQuery(document).on('click', '.aw-button', function() { console.log('Widget clicked!'); });</code>
        </p>
    </div>

    <form method="post" action="options.php">
        <?php settings_fields( 'abjad_widget_code_options' ); ?>

        <div class="abjad-editor-container">
            <div class="abjad-editor-header">
                <h3><?php esc_html_e( 'Your Custom JavaScript', 'abjad-widget' ); ?></h3>
                <p class="description">
                    <?php esc_html_e( 'This code will be executed AFTER the main widget code.', 'abjad-widget' ); ?>
                </p>
            </div>

            <div class="abjad-editor-main">
                <textarea id="custom_js" 
                          name="abjad_widget_code[custom_js]" 
                          class="large-text code" 
                          rows="20"
                          placeholder="<?php echo esc_attr__( '// Write your custom JavaScript here', 'abjad-widget' ); ?>"><?php echo esc_textarea( $abjad_widget_code_options['custom_js'] ); ?></textarea>
            </div>

            <div class="abjad-editor-footer">
                <p class="description">
                    <strong><?php esc_html_e( 'Important', 'abjad-widget' ); ?>:</strong><br>
                    • <?php esc_html_e( 'Your code runs after the main widget code.', 'abjad-widget' ); ?><br>
                    • <?php esc_html_e( 'You cannot directly modify the core widget functions, but you can call them.', 'abjad-widget' ); ?><br>
                    • <?php esc_html_e( 'Faulty code may break the widget. Always backup before making changes.', 'abjad-widget' ); ?>
                </p>
            </div>
        </div>

        <?php submit_button( esc_html__( 'Save JavaScript', 'abjad-widget' ) ); ?>
    </form>

    <div class="abjad-code-reference">
        <h3><?php esc_html_e( 'Available Widget Functions', 'abjad-widget' ); ?></h3>
        <table class="wp-list-table widefat fixed striped">
            <thead>
                <tr>
                    <th><?php esc_html_e( 'Function', 'abjad-widget' ); ?></th>
                    <th><?php esc_html_e( 'Description', 'abjad-widget' ); ?></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><code>calculations('abjad')</code></td>
                    <td><?php esc_html_e( 'Triggers Abjad calculation', 'abjad-widget' ); ?></td>
                </tr>
                <tr>
                    <td><code>calculations('bastet')</code></td>
                    <td><?php esc_html_e( 'Triggers Bastet calculation', 'abjad-widget' ); ?></td>
                </tr>
                <tr>
                    <td><code>calculations('huddam')</code></td>
                    <td><?php esc_html_e( 'Triggers Huddam calculation', 'abjad-widget' ); ?></td>
                </tr>
                <tr>
                    <td><code>switchTab(tabId)</code></td>
                    <td><?php esc_html_e( 'Switches between tabs (abjad/bastet/huddam/settings/support)', 'abjad-widget' ); ?></td>
                </tr>
                <tr>
                    <td><code>getSetting(id)</code></td>
                    <td><?php esc_html_e( 'Reads a widget setting', 'abjad-widget' ); ?></td>
                </tr>
                <tr>
                    <td><code>setSetting(id, value)</code></td>
                    <td><?php esc_html_e( 'Changes a widget setting', 'abjad-widget' ); ?></td>
                </tr>
                <tr>
                    <td><code>__(key)</code></td>
                    <td><?php esc_html_e( 'Returns a translated string', 'abjad-widget' ); ?></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<style>
.abjad-code-editor-page .CodeMirror {
    border: 1px solid #ccd0d4;
    height: auto;
    max-height: 500px;
    font-family: 'Monaco', 'Menlo', 'Consolas', monospace;
    font-size: 13px;
    line-height: 1.5;
    border-radius: 4px;
}

.abjad-code-editor-page .CodeMirror-gutters {
    background: #f8f9fa;
    border-right: 1px solid #ccd0d4;
}

.abjad-code-editor-page .CodeMirror-linenumber {
    color: #666;
}

.abjad-editor-container {
    background: #fff;
    border: 1px solid #ccd0d4;
    border-radius: 4px;
    margin: 20px 0;
}

.abjad-editor-header {
    padding: 15px 20px;
    border-bottom: 1px solid #ccd0d4;
    background: #f8f9fa;
}

.abjad-editor-header h3 {
    margin: 0 0 10px 0;
}

.abjad-editor-main {
    padding: 20px;
}

.abjad-editor-footer {
    padding: 15px 20px;
    border-top: 1px solid #ccd0d4;
    background: #f8f9fa;
}

.abjad-code-reference {
    margin-top: 30px;
    background: #fff;
    border: 1px solid #ccd0d4;
    border-radius: 4px;
    padding: 20px;
}

.abjad-code-reference h3 {
    margin-top: 0;
}

.abjad-code-reference table {
    margin-top: 15px;
}

.abjad-code-reference code {
    background: #f1f1f1;
    padding: 2px 5px;
    border-radius: 3px;
    font-size: 12px;
}

.notice-info {
    border-left-color: #00a0d2;
    background: #f7fcfe;
}
</style>

<script>
jQuery(document).ready(function($) {
    if (typeof wp.codeEditor !== 'undefined') {
        var editor = wp.codeEditor.initialize($('#custom_js'), {
            codemirror: {
                mode: 'javascript',
                lineNumbers: true,
                lineWrapping: true,
                theme: 'default',
                autoCloseBrackets: true,
                matchBrackets: true,
                indentUnit: 4,
                tabSize: 4,
                indentWithTabs: true,
                extraKeys: {
                    'Ctrl-Space': 'autocomplete',
                    'Ctrl-S': function() {
                        $('form').submit();
                    }
                }
            }
        });

        var jsEditor = editor.codemirror;

        jsEditor.on('change', function() {
            // No auto-save
        });
    }

    $('form').on('submit', function(e) {
        var jsCode = $('#custom_js').val();
        if (jsCode.includes('</script>')) {
            if (!confirm('<?php echo esc_js( __( 'Your code contains a </script> tag. This may break the widget. Continue?', 'abjad-widget' ) ); ?>')) {
                e.preventDefault();
                return false;
            }
        }
        return true;
    });
});
</script>
